Cloth_project/cloth_project/cloth_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('clothapp.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                            document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT)                         

Cloth_project/cloth_project/clothapp/urls.py
from django.urls import path

from clothapp import views
app_name='clothapp'


urlpatterns = [
    path('',views.index,name='index'),
    path('cloth/<int:cloth_id>/',views.details,name='details'),
    path('add/',views.add_cloth,name='add_cloth'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),
]

Cloth_project/cloth_project/clothapp/models.py
from distutils.command.upload import upload
from django.db import models
from django.forms import FloatField

# Create your models here.

class Cloth(models.Model):
    name = models.CharField(max_length=250)
    type = models.CharField(max_length=250)
    img = models.ImageField(upload_to='images')
    des = models.TextField()
    price = models.FloatField(max_length=100)

    def __str__(self):
        return self.name

Cloth_project/cloth_project/clothapp/forms.py
from dataclasses import fields
from django import forms
from .models import Cloth

class ClothForm(forms.ModelForm):
    class Meta:
        model = Cloth
        fields = ['name','type','img','des','price']

Cloth_project/cloth_project/clothapp/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect,render

from clothapp.forms import ClothForm
from .models import Cloth

# Create your views here.

def index(request):
    cloth = Cloth.objects.all()
    return render(request,"index.html",{'result':cloth})

def details(request,cloth_id):
    cloth=Cloth.objects.get(id=cloth_id)
    return render(request,"detailed_view.html",{'res':cloth})

def add_cloth(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        type = request.POST.get('type')
        img = request.FILES['img']
        des = request.POST.get('des')
        price = request.POST.get('price')

        cloth = Cloth(name=name,type=type,img=img,des=des,price=price)
        cloth.save()
    return render(request,"add_cloth.html")    

def update(request,id):
    cloth = Cloth.objects.get(id=id)
    form = ClothForm(request.POST or None,request.FILES,instance=cloth)
    if form.is_valid():
        form.save()
        return redirect('/')  
    return render(request,"edit.html",{'cloth':cloth,'form':form})     

def delete(request,id):
    if request.method == 'POST':
        cloth = Cloth.objects.get(id=id)
        cloth.delete()
        return redirect('/')
    return render(request,'delete.html')    

Cloth_project/cloth_project/templates/add_cloth.html
{% extends 'base.html' %}

{% block body %}
<div class="p-5">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3 col-md-6">
          <label for="exampleInputEmail1" class="form-label">Name</label>
          <input type="text" class="form-control" name="name" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="mb-3 col-md-6">
            <label for="exampleInputEmail1" class="form-label">Type</label>
            <input type="text" class="form-control" name="type" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="mb-3 col-md-6">
            <label for="exampleInputEmail1" class="form-label">Image</label>
            <input type="file" class="form-control" name="img" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="mb-3 col-md-6">
            <label for="exampleInputEmail1" class="form-label">Description</label>
            <input type="text" class="form-control" name="des" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="mb-3 col-md-6">
          <label for="exampleInputPassword1" class="form-label">Price</label>
          <input type="number" class="form-control" name="price" id="exampleInputPassword1">
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
      </form>

</div>
{% endblock %}

Cloth_project/cloth_project/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Bootstrap CSS -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
            crossorigin="anonymous"
        >
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <title>Index</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-dark ">
            <div class="container-fluid">
              <a class="navbar-brand text-white" href="#">Navbar</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active text-white" aria-current="page" href="#">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link text-white" href="#">Link</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Dropdown
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <li><a class="dropdown-item text-white" href="#">Action</a></li>
                      <li><a class="dropdown-item text-white" href="#">Another action</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item text-white" href="#">Something else here</a></li>
                    </ul>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link disabled text-white">Disabled</a>
                  </li>
                </ul>
                <form class="d-flex">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-light" type="submit">Search</button>
                </form>
              </div>
            </div>
          </nav>
        {% block body %}



        {% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    </body>
</html>
   

Cloth_project/cloth_project/templates/delete.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    
    Are you sure?
    <button type="submit">Yes</button>
    </form>

Cloth_project/cloth_project/templates/detailed_view.html
{% extends 'base.html' %}
{% block body %}
<div class="p-5">
    <div class="row">
        <div class="card col-md-3 card_view">
            <img src="{{res.img.url}}" class="card-img-top" alt="...">
            <div class="card-body">
            <h5 class="card-title">{{res.name}}</h5>
            <p class="card-text">{{res.type}}</p>
            </div>
            <ul class="list-group list-group-flush">
            <li class="list-group-item">{{res.des}}</li>
            <li class="list-group-item">₹ {{res.price}}</li>
            </ul>
            <div class="card-body">
                <a href="" class="btn btn-primary">Buy</a>
                <a href="" class="btn btn-warning">Cart</a>
                <a href="{% url 'clothapp:update' res.id %}" class="btn btn-warning">Update</a>
                <a href="{% url 'clothapp:delete' res.id %}" class="btn btn-danger">Delete</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Cloth_project/cloth_project/templates/edit.html
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}

{{form.as_p}}
<button type="submit">OK</button>
</form>

Cloth_project/cloth_project/templates/index.html
{% extends 'base.html' %}
      {% block body %}
      <div class="p-5">
        <div class="row">
            {% for res in result %}
             <div class="col-md-3">
                <div class="card mt-3">
                    <img src="{{res.img.url}}" class="card-img-top p-3" width="200" height="350" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{res.name}}</h5>
                        <p class="card-text">{{res.type}}</p>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">{{res.des}}</li>
                        <li class="list-group-item">₹ {{res.price}}</li>
                    </ul>
                    <div class="card-body">
                        <a href="{% url 'clothapp:details' res.id %}" class="btn btn-primary btn-view">View</a>
                        <a href="" class="btn btn-warning">Cart</a>
                    </div>
                </div>
              </div>
            {% endfor %}
        </div>
      </div>
      {% endblock %}  
        